# vim: ts=2 sw=2 et :
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/claiming-service-dev-29824/frontend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80

