import {
  MatAutocompleteModule,
  MatFormFieldModule,
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatChipsModule,
  MatInputModule,
  MatTooltipModule,
  MatSidenavModule,
  MatExpansionModule,
  MatSelectModule,
  MatStepperModule,
  MatTabsModule,
  MatProgressSpinnerModule,
  MatMenuModule,
  MatListModule,
  MatDialogModule,
  MatRadioModule,
} from '@angular/material'

import { NgModule } from '@angular/core'

@NgModule({
  imports: [
    MatAutocompleteModule,
    MatExpansionModule,
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatChipsModule,
    MatFormFieldModule,
    MatInputModule,
    MatTooltipModule,
    MatSidenavModule,
    MatStepperModule,
    MatTabsModule,
    MatSelectModule,
    MatMenuModule,
    MatListModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatRadioModule,
  ],
  exports: [
    MatAutocompleteModule,
    MatExpansionModule,
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatChipsModule,
    MatFormFieldModule,
    MatInputModule,
    MatTooltipModule,
    MatSidenavModule,
    MatStepperModule,
    MatTabsModule,
    MatSelectModule,
    MatMenuModule,
    MatDialogModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatRadioModule,
  ],
})
export class MaterialModule { }
